---
- name: Task4
  hosts: "{{ nodes }}"
  gather_facts: false
  tasks:

  - name: Install prerequisite tools
    become: yes
    ansible.builtin.apt:
      pkg:
      - unzip
      state: present

  - name: Create destination directory
    ansible.builtin.file:
      path: /tmp/java/bin/
      state: directory
      
  - name: Download Gradle binary archive
    ansible.builtin.get_url:
      url: https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
      dest: /tmp/
    register: file_downloaded

  - name: Extract Gradle archive
    unarchive:
      src: "{{ file_downloaded.dest }}"
      dest: /tmp/java/bin/
      remote_src: yes
    register: extracted

  - name: alternative way
    ansible.builtin.shell: |
      export PATH=/tmp/java/bin/;$PATH
      #/tmp/java/bin/gradle-8.2.1/bin/gradle --version
      gradle --version
      exit 0
  - debug: var=extracted
